services:
  - type: web
    name: criminal-case
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false # This means you need to set it manually in the Render dashboard   